services:
    fpm:
        build:
            context: ./
            dockerfile: ./.docker/fpm/Dockerfile
        restart: always
        volumes:
            - ./:/var/www/html
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M


networks:
    default:
        driver: bridge
