
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Cycle\SymfonyBundle\DependencyInjection\Security\EntityUserProvider: ~

    Cycle\SymfonyBundle\Command\:
        resource: '../src/Command/'

    Cycle\SymfonyBundle\Factory\:
        resource: '../src/Factory/'

    Cycle\SymfonyBundle\Migration\:
        resource: '../src/Migration/'

    Cycle\SymfonyBundle\Service\:
        resource: '../src/Service/'

    Cycle\Database\DatabaseProviderInterface:
        factory: ['@Cycle\SymfonyBundle\Factory\DatabaseFactory', 'createDatabaseManager']

    Cycle\ORM\EntityManagerInterface:
        class: Cycle\ORM\EntityManager

    Cycle\ORM\ORMInterface:
        factory: ['@Cycle\SymfonyBundle\Factory\OrmFactory', 'createOrm']

    Cycle\Schema\Registry: ~
