
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Cycle\SymfonyBundle\Factory\DatabaseFactory: ~
    Cycle\SymfonyBundle\Factory\OrmFactory: ~

    Cycle\Database\DatabaseProviderInterface:
        factory: ['@Cycle\SymfonyBundle\Factory\DatabaseFactory', 'createDatabaseManager']

    Cycle\ORM\ORMInterface:
        factory: ['@Cycle\SymfonyBundle\Factory\OrmFactory', 'createOrm']
